In [1]:
def get_char_count(lyric, char):
    count = 0
    for i in lyric:
        if i == char:
            count += 1
    return count

In [2]:
lyric = """산토끼 토끼야. 어디를 가느냐. 깡충깡충 뛰면서. 어디를 가느냐.
산 고개 고개를. 나 혼자 넘어서. 토실토실 알밤을. 주워 올 테야."""

print(get_char_count(lyric, '토'))

4


In [2]:
import numpy as np

In [3]:
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [20]:
np.random.rand(2,3)

array([[0.12864526, 0.47211696, 0.18628699],
       [0.04387615, 0.07560279, 0.66994287]])

In [23]:
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [26]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
arr.shape

(16,)

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [30]:
arr[5]

5

In [31]:
arr[-1]

15

In [32]:
arr[5:8]

array([5, 6, 7])

In [34]:
# 다차원 배열
arr2 = np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
arr2[1]

array([4, 5, 6, 7])

In [36]:
arr2[1][1]

5

In [37]:
arr2[1,2]

6

In [38]:
arr2[1][2]

6

In [41]:
# 불리언 인덱스
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [42]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [43]:
score_arr[score_arr >= 90]

array([90, 95, 90])

In [45]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [46]:
# 주요 연산
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [47]:
arr + 2

array([3, 4, 5, 6])

In [48]:
arr * 2

array([2, 4, 6, 8])

In [49]:
list = [1,2,3,4]
list

[1, 2, 3, 4]

In [50]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [51]:
arr1 = np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [52]:
arr + arr1

array([ 6,  8, 10, 12])

In [53]:
list1 = [5,6,7,8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [54]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [56]:
# 제곱근(루트)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [57]:
# exp(지수승)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [58]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
# 더하기
np.add(arr, arr1)

array([ 6,  8, 10, 12])

In [60]:
# 합계
np.sum(arr)

10

In [61]:
# 누적합
np.cumsum(arr)

array([ 1,  3,  6, 10], dtype=int32)

In [62]:
# 평균
np.mean(arr)

2.5

In [63]:
# 편차
np.var(arr)

1.25

In [64]:
# 표준편차
np.std(arr)

1.118033988749895

In [65]:
# 변형
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [68]:
arr.T # arr.transpose()와 동일

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [69]:
# 저장
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
np.save('array', arr)

In [71]:
load_arr = np.load('array.npy')

In [72]:
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])